In [1]:
import numpy as np

In [2]:
def generer_variables(m):
    M=m+1
    noms_var=["x"+str(i) for i in range(M)]
    R=PolynomialRing(Fq, noms_var)
    return R.gens()

In [3]:
Monomes=[]
def generer_exposants_rec(degre_restant,indice,exp_actuels):
    if indice==(M-1):
        exp_actuels[indice]=degre_restant
        monome=prod(variables[i]^(exp_actuels[i]) for i in range(M))
        Monomes.append(monome)
        
        return(Monomes)
        
    for e in range(degre_restant+1):
        exp_actuels[indice]=e
        generer_exposants_rec(degre_restant-e, indice+1,exp_actuels)
        
    return(Monomes)

In [4]:
def generer_exposants(degre_restant,indice,exp_actuels):
    Monomes=[]
    return(generer_exposants_rec(degre_restant,indice,exp_actuels))

Exemple de la fonction generer_exposants dans F4 avec 5 variables :

In [5]:
q=9
Fq=GF(q)
m=3
M=m+1
variables=generer_variables(m)

Monomes=[] #penser a initialiser avant chaque appel de generer_exposants
print(generer_exposants(0,0,[0]*M))
Monomes=[]
print(generer_exposants(2,0,[0]*M))

[1]
[x3^2, x2*x3, x2^2, x1*x3, x1*x2, x1^2, x0*x3, x0*x2, x0*x1, x0^2]


C'est dans la cellule qui suit que nous définissons les variables utilisées :

In [6]:
q=3
print("Dans Fq où q=",q)
Fq=GF(q)
m=2
M=m+1
r=2
n=((q^M)-1)/(q-1)
if is_prime(q)==False:
    print("Changer de q, choisir q premier")
variables=generer_variables(m)
variables_n=generer_variables(n)
Monomes=[] #penser a initialiser avant chaque appel de generer_exposants
generer_exposants(r,0,[0]*M)
nb_monomes=len(Monomes)
Cx=[]
g=[]
L=[]
Liste=[]
k=0

coef=int(str(q-1)*nb_monomes,q) #base q vers base 10 
#Fq (2<=q<=36): int("q-1"*nb_monomes, q) 
print(coef)

for i in range(1,coef+1): #pour creer les polynomes P
    #parce qu'on veut tous les coef possibles non tous nuls  
    
    Coefs=list(np.base_repr(i,q,0))
    Coefs=['0']*(nb_monomes-len(Coefs))+Coefs
    #print("liste coefs",Coefs)
    #print("liste monomes",Monomes)
    
    P=sum((Monomes[i]*int(Coefs[i])) for i in range(nb_monomes))
    
    k+=1
    #evaluation=int(str(q-1)*len(variables),q) #base 2 vers base 10 
    for m in range(1,n+1): #parce qu'on veut tous les coef possibles non tous nuls  
            liste=list(np.base_repr(m,q,0))
            if (len(variables)-len(liste))>0:
                liste=['0']*(len(variables)-len(liste))+liste
                
            Liste.append(liste)
            liste_valeurs=[int(el) for el in liste]
            P_eval=P(liste_valeurs)
            
            #print("evaluation de P",P_eval)
            #print("liste valeurs",liste_valeurs)
            for i in liste_valeurs:
                if i!=0:
                    #print("i puisance r :",i^r)
                    Cx=P_eval/(i^r)
                    L.append(Cx)
                    break         
            
    g.append(L)
    L=[]
    
    G=matrix(g)

print(G.dimensions())



Dans Fq où q= 3
728
(728, 13)


In [18]:
#print(G)

In [19]:
print("longueur de G':",G.dimensions())
print(k)

longueur de G': (728, 13)
728


In [7]:
def generer_S(k):
    S=random_matrix(Fq,k,k)
    if S.det()==0:
        return(generer_S(k))
    print("det(S)=",S.determinant())
    return(S)


In [8]:
S=generer_S(k)
S.dimensions()
#print(S)

det(S)= 1


(728, 728)

In [9]:
k

728

In [10]:
liste=[]
for t in range(k):
    p=Permutations(G[t])
    p_rand=p.random_element()
    liste.append(p_rand)
GP=matrix(liste) #GP est directement le produit de G et P
GP.dimensions()
    
    

(728, 13)

In [11]:
G_prime=S*GP
print(G_prime, G_prime.dimensions())

[1 0 1 1 1 2 0 1 1 1 2 0 2]
[2 2 2 1 0 2 0 1 1 2 2 0 0]
[2 0 2 0 0 2 0 1 1 0 2 1 1]
[0 2 0 2 2 0 2 2 1 0 1 2 1]
[1 0 1 1 1 0 0 1 2 0 1 2 0]
[0 1 2 1 1 0 2 0 2 0 1 1 1]
[0 0 2 1 0 2 2 1 1 0 1 2 0]
[1 1 2 1 0 2 0 0 0 1 0 0 0]
[2 0 0 1 1 1 1 2 1 0 0 0 1]
[1 2 2 0 0 0 0 0 0 0 2 0 0]
[0 0 0 0 0 0 1 1 1 1 2 1 0]
[1 2 2 2 1 1 1 2 0 2 1 1 1]
[0 1 0 2 1 2 1 1 1 0 2 1 0]
[0 0 1 1 1 2 1 1 2 1 0 2 1]
[2 0 2 1 2 1 0 0 1 0 2 2 0]
[1 0 2 2 0 1 1 2 1 0 1 1 0]
[1 0 0 1 0 0 0 0 0 1 0 1 0]
[1 2 0 0 2 0 1 0 2 2 2 2 0]
[0 2 0 2 2 2 2 1 0 1 0 0 0]
[2 2 0 0 1 2 2 2 1 2 1 1 2]
[1 0 1 2 0 0 1 0 1 1 0 2 2]
[1 2 0 2 2 0 0 2 0 0 1 0 2]
[2 2 0 1 1 2 0 1 1 0 0 0 2]
[0 2 2 1 2 0 1 2 0 1 1 1 0]
[1 2 0 2 0 2 1 0 2 0 1 2 0]
[1 2 0 2 1 1 0 1 2 0 2 1 2]
[2 1 0 2 2 1 0 0 0 2 0 2 2]
[2 2 1 0 2 1 1 1 0 2 2 1 2]
[1 2 1 1 1 2 0 2 0 2 0 1 1]
[2 2 2 0 1 2 0 1 2 1 1 1 1]
[2 0 0 2 1 2 2 0 1 0 0 1 0]
[2 0 1 1 0 2 1 1 2 1 0 0 0]
[2 2 2 0 0 0 0 1 2 0 2 1 2]
[1 1 2 0 2 2 2 0 0 1 1 1 1]
[1 0 0 1 0 0 2 1 0 2 2 1 0]
[2 1 2 0 2 0 1 1 0 1